# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#- script: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
#  displayName: 'Install Azure CLI'
#- script: az login --service-principal --username "3d587273-dcac-47f1-b714-72f244c67c52a"  --password "8ec3a20c-e55e-4341-abec-28d57eab3be1b" --tenant "59b2865a-7fb8-4ccb-ab68-72cbca88fc48c"
#  displayName: 'Log into Azure with service prinicipal'  


- script: terraform init
  displayName: 'Terraform Init Step' 
- script: terraform plan  -input=false
  displayName: 'Terraform Plan Step'   
- script: terraform apply  -auto-approve
  displayName: 'Terraform Apply Step'  
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
